import React from "react";
import PlusIconUrl from "./plus.svg";
import CloseIconUrl from "./close.svg";
import BoxIconUrl from "./box.svg";
import CheckCircleIconUrl from "./check-circle.svg";
import AlertIconUrl from "./alert.svg";
import InfoIconUrl from "./info.svg";
import ErrorIconUrl from "./info-error.svg";
import BoltIconUrl from "./bolt.svg";
import ArrowUpIconUrl from "./arrow-up.svg";
import ArrowDownIconUrl from "./arrow-down.svg";
import FolderIconUrl from "./folder.svg";
import VideoIconUrl from "./videos.svg";
import AudioIconUrl from "./audio.svg";
import GridIconUrl from "./grid.svg";
import FileIconUrl from "./file.svg";
import DownloadIconUrl from "./download.svg";
import ArrowRightIconUrl from "./arrow-right.svg";
import GroupIconUrl from "./group.svg";
import BoxIconLineUrl from "./box-line.svg";
import ShootingStarIconUrl from "./shooting-star.svg";
import DollarLineIconUrl from "./dollar-line.svg";
import TrashBinIconUrl from "./trash.svg";
import AngleUpIconUrl from "./angle-up.svg";
import AngleDownIconUrl from "./angle-down.svg";
import PencilIconUrl from "./pencil.svg";
import CheckLineIconUrl from "./check-line.svg";
import CloseLineIconUrl from "./close-line.svg";
import ChevronDownIconUrl from "./chevron-down.svg";
import ChevronUpIconUrl from "./chevron-up.svg";
import PaperPlaneIconUrl from "./paper-plane.svg";
import LockIconUrl from "./lock.svg";
import EnvelopeIconUrl from "./envelope.svg";
import UserIconUrl from "./user-line.svg";
import CalenderIconUrl from "./calender-line.svg";
import EyeIconUrl from "./eye.svg";
import EyeCloseIconUrl from "./eye-close.svg";
import TimeIconUrl from "./time.svg";
import CopyIconUrl from "./copy.svg";
import ChevronLeftIconUrl from "./chevron-left.svg";
import UserCircleIconUrl from "./user-circle.svg";
import TaskIconUrl from "./task-icon.svg";
import ListIconUrl from "./list.svg";
import TableIconUrl from "./table.svg";
import PageIconUrl from "./page.svg";
import PieChartIconUrl from "./pie-chart.svg";
import BoxCubeIconUrl from "./box-cube.svg";
import PlugInIconUrl from "./plug-in.svg";
import DocsIconUrl from "./docs.svg";
import MailIconUrl from "./mail-line.svg";
import HorizontaLDotsUrl from "./horizontal-dots.svg";
import ChatIconUrl from "./chat.svg";
import MoreDotIconUrl from "./moredot.svg";
import AlertHexaIconUrl from "./alert-hexa.svg";
import ErrorHexaIconUrl from "./info-hexa.svg";

const make = (src: string, name?: string) =>
  function Icon(props: React.ImgHTMLAttributes<HTMLImageElement>) {
    const { alt, ...rest } = props;
    return React.createElement("img", {
      src,
      alt: alt ?? name ?? "icon",
      ...rest,
    });
  };

export const ErrorHexaIcon = make(ErrorHexaIconUrl, "ErrorHexaIcon");
export const AlertHexaIcon = make(AlertHexaIconUrl, "AlertHexaIcon");
export const MoreDotIcon = make(MoreDotIconUrl, "MoreDotIcon");
export const DownloadIcon = make(DownloadIconUrl, "DownloadIcon");
export const FileIcon = make(FileIconUrl, "FileIcon");
export const GridIcon = make(GridIconUrl, "GridIcon");
export const AudioIcon = make(AudioIconUrl, "AudioIcon");
export const VideoIcon = make(VideoIconUrl, "VideoIcon");
export const BoltIcon = make(BoltIconUrl, "BoltIcon");
export const PlusIcon = make(PlusIconUrl, "PlusIcon");
export const BoxIcon = make(BoxIconUrl, "BoxIcon");
export const CloseIcon = make(CloseIconUrl, "CloseIcon");
export const CheckCircleIcon = make(CheckCircleIconUrl, "CheckCircleIcon");
export const AlertIcon = make(AlertIconUrl, "AlertIcon");
export const InfoIcon = make(InfoIconUrl, "InfoIcon");
export const ErrorIcon = make(ErrorIconUrl, "ErrorIcon");
export const ArrowUpIcon = make(ArrowUpIconUrl, "ArrowUpIcon");
export const FolderIcon = make(FolderIconUrl, "FolderIcon");
export const ArrowDownIcon = make(ArrowDownIconUrl, "ArrowDownIcon");
export const ArrowRightIcon = make(ArrowRightIconUrl, "ArrowRightIcon");
export const GroupIcon = make(GroupIconUrl, "GroupIcon");
export const BoxIconLine = make(BoxIconLineUrl, "BoxIconLine");
export const ShootingStarIcon = make(ShootingStarIconUrl, "ShootingStarIcon");
export const DollarLineIcon = make(DollarLineIconUrl, "DollarLineIcon");
export const TrashBinIcon = make(TrashBinIconUrl, "TrashBinIcon");
export const AngleUpIcon = make(AngleUpIconUrl, "AngleUpIcon");
export const AngleDownIcon = make(AngleDownIconUrl, "AngleDownIcon");
export const PencilIcon = make(PencilIconUrl, "PencilIcon");
export const CheckLineIcon = make(CheckLineIconUrl, "CheckLineIcon");
export const CloseLineIcon = make(CloseLineIconUrl, "CloseLineIcon");
export const ChevronDownIcon = make(ChevronDownIconUrl, "ChevronDownIcon");
export const PaperPlaneIcon = make(PaperPlaneIconUrl, "PaperPlaneIcon");
export const EnvelopeIcon = make(EnvelopeIconUrl, "EnvelopeIcon");
export const LockIcon = make(LockIconUrl, "LockIcon");
export const UserIcon = make(UserIconUrl, "UserIcon");
export const CalenderIcon = make(CalenderIconUrl, "CalenderIcon");
export const EyeIcon = make(EyeIconUrl, "EyeIcon");
export const EyeCloseIcon = make(EyeCloseIconUrl, "EyeCloseIcon");
export const TimeIcon = make(TimeIconUrl, "TimeIcon");
export const CopyIcon = make(CopyIconUrl, "CopyIcon");
export const ChevronLeftIcon = make(ChevronLeftIconUrl, "ChevronLeftIcon");
export const UserCircleIcon = make(UserCircleIconUrl, "UserCircleIcon");
export const TaskIcon = make(TaskIconUrl, "TaskIcon");
export const ListIcon = make(ListIconUrl, "ListIcon");
export const TableIcon = make(TableIconUrl, "TableIcon");
export const PageIcon = make(PageIconUrl, "PageIcon");
export const PieChartIcon = make(PieChartIconUrl, "PieChartIcon");
export const BoxCubeIcon = make(BoxCubeIconUrl, "BoxCubeIcon");
export const PlugInIcon = make(PlugInIconUrl, "PlugInIcon");
export const DocsIcon = make(DocsIconUrl, "DocsIcon");
export const MailIcon = make(MailIconUrl, "MailIcon");
export const HorizontaLDots = make(HorizontaLDotsUrl, "HorizontaLDots");
export const ChevronUpIcon = make(ChevronUpIconUrl, "ChevronUpIcon");
export const ChatIcon = make(ChatIconUrl, "ChatIcon");
